# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlom0dRoeU_3fkoD4gCPQdT44OwbqwCM
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle

df=pd.read_csv('/content/drive/MyDrive/BankNote/BankNote_Authentication (1).csv')

X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

BankNote=RandomForestClassifier()
BankNote.fit(X_train,y_train)

y_pred=BankNote.predict(X_test)

from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

score

pickle_out = open("BankNote.pkl","wb")
pickle.dump(BankNote, pickle_out)
pickle_out.close()
